---
- name:
  shell: >
    getent passwd heywoodlh | cut -d: -f6
  changed_when: false
  register: user_home

- name: "Check if {{ user_home.stdout }}/.nix-profile/bin/{{ item }} exists"
  ansible.builtin.command: "ls -l {{ user_home.stdout }}/.nix-profile/bin/{{ item }}"
  register: flake_check
  ignore_errors: true

- name: Install flake if it doesn't exist
  ansible.builtin.shell: "/nix/var/nix/profiles/default/bin/nix --extra-experimental-features 'nix-command flakes' profile install github:heywoodlh/flakes#{{ item }} --no-write-lock-file"
  when: flake_check is failed
  args:
    executable: /bin/bash
  become_user: heywoodlh
  become: true
