---
- name: create heywoodlh
  ansible.builtin.user:
    name: heywoodlh

- name: remove sudo configuration from archinstall script if exists
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    state: absent
    line: "heywoodlh ALL=(ALL) ALL"
    validate: 'visudo -cf %s'
  loop:
  - /etc/sudoers
  - /etc/sudoers.d/heywoodlh

- name: "Get user home dir"
  shell: >
    getent passwd heywoodlh | cut -d: -f6
  changed_when: false
  register: user_home

- name: create fish directory
  ansible.builtin.file:
    path: "{{ user_home }}/.config/fish"
    owner: heywoodlh
    state: directory
    recurse: true

- name: "Add ansible-switch alias to {{ user_home.stdout }}/.config/fish/custom.fish"
  ansible.builtin.lineinfile:
    path: "{{ user_home.stdout }}/.config/fish/custom.fish"
    create: true
    owner: heywoodlh
    line: "alias ansible-switch \"nix run 'github:heywoodlh/flakes/$(git ls-remote https://github.com/heywoodlh/flakes | head -1 | awk '{print $1}')?dir=ansible#workstation'\""
  become_user: heywoodlh
  become: true
