---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudtube
  namespace: @namespace@
  labels:
    app.kubernetes.io/name: cloudtube
    app.kubernetes.io/instance: cloudtube
---
apiVersion: v1
kind: Service
metadata:
  name: cloudtube
  namespace: @namespace@
  labels:
    app.kubernetes.io/name: cloudtube
    app.kubernetes.io/instance: cloudtube
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "cloudtube"
    tailscale.com/tags: "tag:http"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: cloudtube
    app.kubernetes.io/instance: cloudtube
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudtube
  namespace: @namespace@
  labels:
    app.kubernetes.io/name: cloudtube
    app.kubernetes.io/instance: cloudtube
spec:
  replicas: @replicas@
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudtube
      app.kubernetes.io/instance: cloudtube
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloudtube
        app.kubernetes.io/instance: cloudtube
    spec:
      serviceAccountName: cloudtube
      securityContext:
        {}
      containers:
        - name: cloudtube
          securityContext:
            {}
          image: "@image@"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 10412
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
          env:
            - name: INSTANCE_URI
              value: "http://second.@namespace@.svc.cluster.local"
---
apiVersion: v1
kind: Pod
metadata:
  name: "cloudtube-test-connection"
  namespace: @namespace@
  labels:
    app.kubernetes.io/name: cloudtube
    app.kubernetes.io/instance: cloudtube
spec:
  containers:
    - name: curl
      image: docker.io/curlimages/curl
      command: ['curl']
      args: ["cloudtube.@namespace@.svc.cluster.local:80"]
  restartPolicy: OnFailure
