---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-bedrock
  labels:
    app: minecraft-bedrock
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "minecraft"
    tailscale.com/tags: "tag:minecraft"
spec:
  type: ClusterIP
  ports:
  - name: minecraft
    port: 19132
    targetPort: minecraft
    protocol: UDP
  selector:
    app: minecraft-bedrock
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-bedrock
  labels:
    app: minecraft-bedrock
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: minecraft-bedrock
  template:
    metadata:
      labels:
        app: minecraft-bedrock
    spec:
      securityContext:
        fsGroup: 2000
        runAsGroup: 3000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: minecraft-bedrock
        image: "@image@"
        imagePullPolicy: Always
        stdin: true
        tty: true
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          exec:
              command:
                - mc-monitor
                - status-bedrock
                - --host
                # force health check against IPv4 port
                - 127.0.0.1
                - --port
                - "19132"
          initialDelaySeconds: 30
        livenessProbe:
          exec:
              command:
                - mc-monitor
                - status-bedrock
                - --host
                # force health check against IPv4 port
                - 127.0.0.1
                - --port
                - "19132"
          initialDelaySeconds: 30

        env:
        - name: EULA
          value: "TRUE"
        - name: VERSION
          value: "LATEST"
        - name: DIFFICULTY
          value: "normal"
        - name: SERVER_NAME
          value: "heywoodlh server"
        - name: WHITE_LIST
          value: ""
        - name: WHITE_LIST_USERS
          value: ""
        - name: OPS
          value: "[2533274841530057]"
        - name: MEMBERS
          value: ""
        - name: VISITORS
          value: ""
        - name: ALLOW_CHEATS
          value: "true"
        - name: MAX_PLAYERS
          value: "40"
        - name: VIEW_DISTANCE
          value: "20"
        - name: TICK_DISTANCE
          value: "8"
        - name: PLAYER_IDLE_TIMEOUT
          value: "30"
        - name: MAX_THREADS
          value: "8"
        - name: GAMEMODE
          value: "survival"
        - name: LEVEL_TYPE
          value: "DEFAULT"
        - name: LEVEL_NAME
          value: "heywoodlh world"
        - name: LEVEL_SEED
          value: ""
        - name: DEFAULT_PLAYER_PERMISSION_LEVEL
          value: "member"
        - name: TEXTUREPACK_REQUIRED
          value: "false"
        - name: ONLINE_MODE
          value: "true"
        - name: EMIT_SERVER_TELEMETRY
          value: "false"
        - name: ENABLE_LAN_VISIBILITY
          value: "true"
        - name: SERVER_PORT
          value: "19132"

        ports:
        - name: minecraft
          containerPort: 19132
          protocol: UDP

        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: datadir
          mountPath: /data
        - name: moddir
          mountPath: /mods
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
      volumes:
      - name: tmp
        emptyDir: {}
      - hostPath:
          path: @hostfolder@/data
          type: Directory
        name: datadir
      - hostPath:
          path: @hostfolder@/mods
          type: Directory
        name: moddir
      nodeSelector:
        kubernetes.io/hostname: @nodename@
