---
apiVersion: v1
kind: Namespace
metadata:
  name: @namespace@
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-nfs
  namespace: @namespace@
spec:
  selector:
    matchLabels:
      app: media-nfs
  template:
    metadata:
      labels:
        app: media-nfs
    spec:
      nodeSelector:
        env: home
      containers:
      - name: nfs-server
        image: k8s.gcr.io/volume-nfs:0.8
        ports:
        - name: nfs
          containerPort: 2049
        - name: mountd
          containerPort: 20048
        - name: rpcbind
          containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
        - name: media
          mountPath: /exports
      volumes:
      - name: media
        nfs:
          server: 100.107.238.93
          path: /media/home-media
---
apiVersion: v1
kind: Service
metadata:
  name: media-nfs
  namespace: @namespace@
  annotations:
    tailscale.com/expose: true
    tailscale.com/hostname: "nfs-media"
    tailscale.com/tags: "tag:nfs-media"
spec:
  ports:
  - name: nfs
    port: 2049
  - name: mountd
    port: 20048
  - name: rpcbind
    port: 111
  selector:
    app: media-nfs
