---
apiVersion: v1
kind: Service
metadata:
  name: second
  namespace: @namespace@
  labels:
    app.kubernetes.io/name: second
    app.kubernetes.io/instance: second
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "second"
    tailscale.com/tags: "tag:http"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: second
    app.kubernetes.io/instance: second
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second
  namespace: @namespace@
  labels:
    app.kubernetes.io/name: second
    app.kubernetes.io/instance: second
spec:
  replicas: @replicas@
  selector:
    matchLabels:
      app.kubernetes.io/name: second
      app.kubernetes.io/instance: second
  template:
    metadata:
      labels:
        app.kubernetes.io/name: second
        app.kubernetes.io/instance: second
    spec:
      serviceAccountName: default
      securityContext:
        {}
      containers:
        - name: second
          securityContext:
            {}
          image: "@image@"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
---
apiVersion: v1
kind: Pod
metadata:
  name: "second-test-connection"
  namespace: @namespace@
  labels:
    app.kubernetes.io/name: second
    app.kubernetes.io/instance: second
spec:
  containers:
    - name: curl
      image: docker.io/curlimages/curl
      command: ['curl']
      args: ["second.@namespace@.svc.cluster.local:80"]
  restartPolicy: OnFailure
