---
- name: install arch packages
  community.general.pacman:
    name: "{{ item }}"
    update_cache: yes
  with_items:
  - cronie
  - git
  - curl
  - python-pip
  - sudo
  - tailscale
  - ufw
  when: ansible_os_family == 'Archlinux'

- name: install debian packages
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
  - git
  - curl
  - python3-pip
  - sudo
  - ufw
  when: ansible_os_family == 'Debian'

- name: install tailscale
  ansible.builtin.shell: |
    curl https://tailscale.com/install.sh | bash
  when: ansible_os_family != 'Archlinux'

- name: enable cronie service
  ansible.builtin.systemd:
    name: cronie.service
    enabled: yes
    state: started
  when: ansible_os_family == 'Archlinux'

- name: uninstall firefox snap
  when: ansible_distribution == "Ubuntu"
  block:
  - name: disable firefox snap service
    ansible.builtin.shell: systemctl disable --now var-snap-firefox-common-host\\x2dhunspell.mount

  - name: remove firefox snap
    community.general.snap:
      name: firefox
      state: absent
