---
- name: "Get user home dir"
  shell: >
    getent passwd heywoodlh | cut -d: -f6
  changed_when: false
  register: user_home

- name: "Check if {{ user_home.stdout }}/.nix-profile/bin/{{ item }} exists"
  ansible.builtin.command: "ls -l {{ user_home.stdout }}/.nix-profile/bin/{{ item }}"
  register: flake_check
  ignore_errors: true

- name: Install flake if it doesn't exist
  ansible.builtin.shell: "nix --extra-experimental-features 'nix-command flakes' profile install github:heywoodlh/flakes?dir={{ item }} --impure"
  when: flake_check.rc != 0
  args:
    executable: /bin/bash
  environment:
    NIXPKGS_ALLOW_UNFREE: 1
  become_user: heywoodlh
  become: true
