name: build-all-flakes

on:
  push:
    branches:
    - 'main'
    paths:
    - '*'
    - '!**.md'
    - '!kube/**'
  schedule:
  - cron: '0 0 * * Wed' # To update flake.lock
  workflow_dispatch:

jobs:
  build-flakes:
    name: Build all flakes
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main

    - name: Setup Nix Magic Cache
      uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Build flakes
      run: |
        nix flake update ./fish
        nix flake update ./vim
        nix flake update ./tmux
        nix flake update ./git
        nix flake update ./vscode
        nix flake update ./wezterm
        nix flake update ./st
        nix flake update ./jetporch
        nix flake update .

    - name: If scheduled or manually triggered, add updated flake.lock if changed, commit and push
      uses: EndBug/add-and-commit@v9
      with:
        add: './'
        author_name: 'github-actions'
        author_email: 'github-actions@github.com'

