name: build-meta-flake-envs

on:
  push:
    branches:
    - 'main'
    paths:
    - '**'
    - '!**.md'
  schedule:
  - cron: '0 0 * * Wed' # To update flake.lock
  workflow_dispatch:

jobs:
  build-flakes:
    name: Build all flakes
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@main

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main

    - name: Setup Nix Magic Cache
      uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Build flakes
      run: |
        nix flake update ./fish
        nix flake update ./vim
        nix flake update ./tmux
        nix flake update ./git
        nix flake update ./vscode
        nix flake update ./wezterm
        nix flake update ./st

    - name: Add updated flakes
      uses: EndBug/add-and-commit@main
      with:
        add: './'
        author_name: 'github-actions'
        author_email: 'github-actions@github.com'

    - name: Build meta flake
      run: |
        nix flake update .

    - name: Updated flake.lock
      uses: EndBug/add-and-commit@main
      with:
        add: './flake.lock'
        author_name: 'github-actions'
        author_email: 'github-actions@github.com'
