name: build-flakes

on:
  push:
    branches:
    - 'main'
    paths:
    - '**'
    - '!**.md'
  schedule:
  - cron: '0 0 * * Wed' # To update flake.lock
  workflow_dispatch:

jobs:
  build-flakes:
    name: Build all flakes
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@main

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main

    - name: Setup Nix Magic Cache
      uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Update fish
      uses: DeterminateSystems/update-flake-lock@main
      with:
        path-to-flake-dir: 'fish/'

    - name: Update tmux
      uses: DeterminateSystems/update-flake-lock@main
      with:
        path-to-flake-dir: 'tmux/'

    - name: Update vim
      uses: DeterminateSystems/update-flake-lock@main
      with:
        path-to-flake-dir: 'vim/'

    - name: Update wezterm
      uses: DeterminateSystems/update-flake-lock@main
      with:
        path-to-flake-dir: 'wezterm/'

    - name: Update st
      uses: DeterminateSystems/update-flake-lock@main
      with:
        path-to-flake-dir: 'st/'

    - name: Update vscode
      uses: DeterminateSystems/update-flake-lock@main
      with:
        path-to-flake-dir: 'vscode/'
