name: kubernetes cd

on:
  workflow_dispatch:
    inputs:
      deployment:
        description: "Which Kubernetes deployment to build"
        required: true

jobs:
  deploy-services:
    name: Check and apply all deployments
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Connect to Tailnet
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:ci

    - name: Install Nix
      uses: cachix/install-nix-action@v26
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Setup Nix Magic Cache
      uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Configure kubectl
      uses: tale/kubectl-action@v1
      with:
        base64-kube-config: ${{ secrets.KUBECONFIG }}

    - name: Check Kubernetes deployment diff
      id: check
      run: |
        cd kube
        nix build -o ./result .#"${{ github.event.inputs.deployment }}"
        kubectl diff -f ./result | grep -vE 'generation|LIVE|MERGED' | grep -E '^-|^\+' && echo changed="true" >> $GITHUB_ENV || true

    - name: Apply Kubernetes deployment if changed
      if: ${{ env.changed == 'true' }}
      run: |
        cd kube
        nix build -o ./result .#"${{ github.event.inputs.deployment }}"
        kubectl apply -f ./result
