name: build-vim-envs

on:
  push:
    branches:
    - 'main'
    paths:
    - vim/**
    - .github/workflows/vim.yml
  schedule:
  - cron: '0 0 * * Thu' # To update flake.lock
  workflow_dispatch:

jobs:
  setup:
    name: Setup nix
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main

    - name: Setup Nix Magic Cache
      uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Update inputs again
      run: |
        nix flake update ./fish

    - name: Build fish flake
      run: |
        nix build ./fish#

    - name: Add updated flake.lock if changed, commit and push
      uses: EndBug/add-and-commit@v9
      with:
        add: 'fish/flake.lock'
        author_name: 'github-actions'
        author_email: 'github-actions@github.com'

    - name: Update vim inputs
      run: |
        nix flake update ./vim

    - name: Build vim flake
      run: |
        # Build vim flake
        nix build ./vim#

    - name: Add updated vim flake.lock if changed, commit and push
      uses: EndBug/add-and-commit@v9
      with:
        add: 'vim/flake.lock'
        author_name: 'github-actions'
        author_email: 'github-actions@github.com'
